project:
  type: website

website:
  title: "K-6 Computer Literacy Program"
  search:
    location: navbar
  reader-mode: false
  back-to-top-navigation: true
  page-navigation: true
  favicon: "icons/favicon.ico"
  navbar:
    right:
      - text: "Tech Leader Guide"
        href: "tech-leader-guide/index.qmd"
      - text: "Activities"
        href: "activities/index.qmd"
      - text: "About"
        href: "about/index.qmd"

  page-footer:
    right:
      - icon: github
        href: https://github.com/K-6-computing-literacy
      

format:
  html:
    mainfont: Inter
    monofont: Ubuntu Mono
    fontsize: 1.25em
    theme: materia
    highlight-style: github
    css: styles.css

execute:
  freeze: auto

